### ISSUE TITLE
ContactUs Form Not Fully Visible, Footer is overlapping it

### ISSUE THREAD

**Issue by vipinkhushu** [Mozpacers/Mozpacers.github.io#43] opened 2016-01-24 21:07 UTC
![screenshot 216](https://cloud.githubusercontent.com/assets/11455744/12538919/54af6350-c30c-11e5-8baf-0ed03174be57.png)
 Steps to reproduce
1.Open http://www.mozpacers.org
2.Go to contact us form and this issue will be visible

This issue is due to a small problem in CSS of footer

**Comment by handasolo** [comment] 2016-01-25 21:21
Seems to be a chrome specific problem. Can you try in firefox and post the result?

**Comment by vipinkhushu** [comment] 2016-01-26 09:39
@Slayslot I have found a fix to this bug, after the fix this problem seems to be resolved and site is looking perfectly okey in both Chrome And Mozilla Firefox.
Shall i send the pr for this fix

**Comment by handasolo** [comment] 2016-01-26 09:42
Test it thoroughly first and if you feel everything is good, push it with the PR you already have open.

**Comment by vipinkhushu** [comment] 2016-01-31 11:33
#43 Fixed
Check #42 PR

**Comment by CuriousLearner** [comment] 2016-02-08 14:01
Since this was terribly cluttering the site in mobile mode ( the submit button was hidden ), I've issued a fix for this. You shall do the AJAX loader part. Thanks :)

**Comment by CuriousLearner** [comment] 2016-02-11 19:11
This bug is still confirmed on Chrome both in Desktop and Mobile.

@Slayslot Assigning this to you.

**Comment by handasolo** [comment] 2016-02-12 17:39
@vipinkhushu @CuriousLearner @yash14123 @ManrajGrover @h4xr Thoroughly check and close please.

**Comment by CuriousLearner** [comment] 2016-02-12 17:43
I've checked this. Closing this. Thanks @Slayslot 

Others, if you find issue, re-open this.

**Closed as completed by CuriousLearner** 2016-02-12 17:43 UTC
