### ISSUE TITLE
Footer located too close to the message box in the "Contact us" section. Needs some margining.

### ISSUE THREAD

**Issue by theaverageguy** [Mozpacers/Mozpacers.github.io#46] opened 2016-02-08 14:32 UTC

**Comment by CuriousLearner** [comment] 2016-02-08 15:53
If you feel it is, can you please post a screenshot?

**Comment by manrajgrover** [comment] 2016-02-09 03:51
This only occurs in Chrome

![untitled1212](https://cloud.githubusercontent.com/assets/5673050/12907186/75ea9ba8-cf0e-11e5-9599-4145ea082c38.png)

**Comment by manrajgrover** [comment] 2016-02-09 03:58
Related to #43 I guess

**Comment by CuriousLearner** [comment] 2016-02-09 12:25
This is appearing on Chrome, not on Firefox @ManrajGrover

**Comment by manrajgrover** [comment] 2016-02-09 13:17
That is what I said @CuriousLearner

**Comment by CuriousLearner** [comment] 2016-02-11 14:11
Duplicate of #43

**Closed as completed by CuriousLearner** 2016-02-11 14:11 UTC
