### ISSUE TITLE
Text not properly visible in events section

### ISSUE THREAD

**Issue by h4xr** [Mozpacers/Mozpacers.github.io#72] opened 2016-02-17 16:52 UTC
Longer addresses aren't properly visible in the events section

![screenshot from 2016-02-17 22 21 06](https://cloud.githubusercontent.com/assets/7107127/13117178/e6e18a9e-d5c4-11e5-863e-59e0d6a0ab43.png)

**Comment by handasolo** [comment] 2016-02-17 17:13
Duplicate of #54

**Closed as completed** 2016-02-17 17:13 UTC
